apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    categories: Monitoring, Logging & Tracing
    repository: https://github.com/korrel8r/korrel8r
    support: Korrel8r Project
  name: korrel8r.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Korrel8r is a service that correlates observabililty signals in
        the cluster.
      displayName: Korrel8r
      kind: Korrel8r
      name: korrel8rs.korrel8r.openshift.io
      version: v1alpha1
  description: Korrel8r is a correlation engine that relates Kubernetes objects to
    different types of obsevable signal data.
  displayName: Korrel8r
  icon:
  - base64data: |
      iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAC1tJREFUaAXtWAdYU9cevxn3ZpNAIGwFB5QqGEVFsLIUB7ZaF1YRfVhU6it18UTah0WfA8UBSqGIUq08rXWPKq3PupDKFmQTAkYCMgIC2eu+e9EggSSEvtb39fs8fOSc8z+//zzrfy4GhuFI4C9csH9h23tMf+fA/3sG8UM14OpPlxwfZz0aIxFJyaNcnTjhoX9/gsfj1UOV80fhMUPZxF9t3Tqv+kmVxwLuYpAip2DuONyWCawFgiPJKclMJlP2Rxk1FDlGO3D2Qobz1dRLK0/cOw1RlJQeHTAAA3HsXUqBT1v+gYTEi0NRbAjb3NpMRAOCx+JhQzh0zOgllP1Llseqik97jUeZMcjfuor1+BU2QeOR7v/swI3Maw5Hz5xYLu3uomEAAJ7AnvgoLnr3LQiC9C5Ro0+hzvZOcxuJDWq3VjGTMQGlWokXCAQErYEhdkrLS0wPnjgalh8RZfrg8l189neXwIcioVdM/PaZhkQZ7YCZpVkTh1YzYEr55AYAwhCUvMZ6qiFFg419fzFjCi9wAdg+yasHqmCYAiVR/4LyCnKnqdVqZEJ0F6OX0NxF8x4mcQ+P9WydCtmIbXukyXAy4CB7n5xpzXy2LWZLhL3dMM7ShcH3AvxnNaAAuVyOPXBkpzeHW+QK4kHFeDff3PCwjYW6TOG1NNuJvPy0AipnmgMqGMC2tDURrVi2El18RjuAGlVUUJAZigkO9G7xVVPlNGyW9QOV5UirirSEU2e7u7vBYyeTJyckx686firl5dzZ8+/efXjZ14JZZxv+6XNIJsMC6aef29c3VNvHxSZf7egQQFdvXhmdV5jzHre+1gVWq7HmT/KUzdPn9NpE5VYDIAGS6TMedcjoUwgFb/t6y2yBoIU5dsz4KrFYRHJnu9fPnB74HB3TFIlEgjuRcWzcrZ9vzLKxEVBTE4sg7OsFIBLhgKWhExUUkhVf0C6wZrEseWNcXCuR4FQMt3fsDo5YFVX30WJSk+8sHKmJD7gcjZN/Mm36xc/DInTOGqqz11uNAfpqXkM9pbA433P/zoREttv4dn04Eomk+nzNhsJnvCp7d3bZVI3xKJ5CUQGTxgvhjpc2/KRDacctmBZad8e3e44c2pVy8OOGW1ccccjCd7S0rjFkPCrTaAcSUw75ve88psiQ8ahATSESqGKhEEQ3vdYGFEtw6nGubE5/41G+USOcuk/Gp55G25m3b9onpR4ORjcwFosdcHigGLRobZpXpIG/NbVVJk9Ln0z6LCzi7sBR3RR/n5ll129ZK9sEUC+goooKlFXSgAD/QG4vUU9jdkDgcxAiyC5fvzBCD6SHbNQMJB1LnD5u7Pg859EunYaE9R3zmzaj8cy576pC1mJc/L3bYakUDz/OZ8DLl4SdsbOxE/fF6mtPnjglN/POTY9F84Nq9WF0OlBUXMD88cbZiR2iDhNrE2tBeWUpOzXxZLw+IbroObm/sXh8vuO60M1pyCnDYjAgZULc3OrRI527dOF10UJXhBauCFs2q7yqlAGBkApdYv1xAxxISk+YcD7z3CL+rCa8hCXFWmezFEyiqVQsFoL9mfX10fM/PmnvJ7NnfJi5cN4SdLkMumR0yersFII0EJJs3LRmG1EFqwEIVMxbuOxSWOj6Yg1ey4GConzzC7fOLco7/ASS2El7MI0fNYPDztviY45Eh1xMvn5U14ZSKpVYNM3m1nMsRzk6NReVFDggEZNu+GxzrkbRUOvO7k4wOnLdFwvLa6nLavk4PAzjqk0o4D9lsiAYh4XXrAwvQWVqOXD2WoYHbx4f1BivUcpbzMcMv2bLysvPsfCY7NmioaN1Q2MDOSoqYg0glFs44M2wP957qG5XS9Qx0bHJupzty2uonfJtwhTXxhZyCKcBp8E5dYmAHbkVUDTxzAKdDvAE9fZdM4Vax14PM0IRj5TAP/1yzdWCZZkzwmGEUCN0z96YhSOlVKsldDYezU7VSIp9trtQde6HM34fTPE9q8EZqpFbHN/4opHc0tZMam9vI7/sfEkuL8xjr+S3DFi2Lp1CQCmXE7j1XCpqh9YMmFGZAkIrNFKXMmITESjuLGaHbwz1VqthLN2E3sZgmAqe1dW6hpnPR+6rV35jkXoh1Q33Zc0Nt2+OH6mUiETELmE3WSQWkpDbm4zc1CSpVEqWyKRkmUxKkstkZORdgSFARDGBAEkIBKKYSCRKJIAKFON7g99rEprWKTAYDJ1GV6BELQd82H4lT6+WsJsCWyC4z1vCpJwGEDuJqoy0c4k0Gk2JLpun5cXmRUX5w1ueN7hAGPybwx4RSsKAAA6DhXPystl0E0YnhUSWMOiMbnvbYc10ExMJncEUMxlmEpYFS2zFspKYmjLlvRa+bqR9/63b1ebWoLkNrQQc/OYeu21rAZvTTFo0L0AtB5YFrajKzL1ZqYhUOleFcwhSlgwwLaTDzmmjFKsXr/kBNR6Vj57jyD8vwHdWw5x7twOFsAygYt48B7rUUkCFLKb0lIyTxryq+huP9jEwBubTyKrNXq7y0Ip6iC5XANlWTPUZp2GKbRu//EHDg4uNjX2VgL+mzJ+x4KmA0yZTnpezbC9bYexKbLscmMNrv/pH7IBbGN2kZaXF1KIX1dZuoC0Oh8EAclgJpAtzFDIC5qXHxCklZjqiq1Gur04+fnTClRsX5kVujj4uJFParxNg2s1hVqqXbmOrt8XEnZo0waNVwztoNsrlcmjhm1ZHpn+Tsc/ObtiAG5TXwKOs/WJVJKiAITsCU8WTt+MdhjuWMa2sXiCpsucX4ZtOzwn48JlG4WB1fOIerzv3/+OPBCxtmqd382D4ATPQn8HU1Ez+KCfLsoZbY+r7gX99//Hd+78OIBEpwq2R2zMIFvS6kODVv4SuWpvr5z29DpmhltT0b4LbBG1Sz8le/P68/fs74mL8sh9nTd0duz/Vw92zN8r9cX37Wnug70DfdnDQyge7D+z4VCQRPaCQkJz4dckvyDUvLn0yOelg6iE0ReifqS5fElLpNMI5edeB2L9xuNV2+3cdvoJF8se9iXu8S6qrxkI4UD7Hx+fRquVhZVHbNwdWcypdDu5NSnYebXy6MegS0hi7bPXiddO8fPLW93lcrFgTFDYWeZBs2xyTpcHpqtHPJFExmz4RS8QUiVJN4uNMzJ4huwanVACjn2XLLUm4ViQtVibGp5ywtdL9dNQlF6UZlU6jwDkBcx/cufezN9pGy7HvUsZ1C4X0DZ9F/vaKov/X0sJSmp6ccQqLA5XPcXTTojHzwXYzR6CV5QTkTAiGWoViFpJx3h6q8ahGox1AlkMVEkHq0hX+0SGhAVsuXjm3ICxk7SX0Babf9Dcj6InV1tVtWeP4gdadocKBANd+Mvjrb1nsN2jjW0btAVTczr1bZw4z6yBtmMuB5CossO+yk4JTV2mJDNUZow75doRRSLooEhJjAFxCZgItzdWorCEXo2YAfdblFDz23hNcBr1vLwTYDl3AjqUVYNajWzOM1YheaHgSVUKQDXwOEKWdgDmd0WasrL44oxxoFbQSkN2OZdJ60o8efnumFOgSyl99JO0r0UDbeeTop478wp7bXAPDIGk+QpP5eEwt0tCGUhvlALoJqRRidz6H3iv7XjkTtrE0a+wlGNHYvuXLm/YddaL3an9VUkRtgElXE+Becl7maGnOWbkstMIIEQMgg15kGg48gcY/9G+O24sOEny/1EJ9KcdOHrF++/fD7R16U2sNVl9NpZgoZ/oF5NYV3KdRanNoDl31whnu7vcP7zx4DUkw9bEZpBt9D6BSkA+wjJ8yr40BIVD18YdLSvu+Cwxq+RMHh+TAn2jH7xZt1B743dLfAuM7B95CkA2qeDcDBsPzFgbfzcBbCLJBFe9mwGB43sLgfwFYuaLFnR4iugAAAABJRU5ErkJggg==
    mediatype: image/png
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - observability
  - signal
  - correlation
  links:
  - name: Documentation
    url: https://korrel8r.github.io/korrel8r
  - name: Source Code and Issues
    url: https://github.com/korrel8r/korrel8r
  maintainers:
  - email: korrel8r@gmail.com
    name: Korrel8r Project
  maturity: alpha
  minKubeVersion: 1.23.0
  provider:
    name: The Korrel8r Project
    url: https://github.com/korrel8r/korrel8r
  version: 0.0.0
